apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
  - image: vacations-service
    context: ../services/vacations-service
    jib:
      project: vacations-service
  - image: vacation-portal
    context: ../web/vacation-portal
    sync:
      infer:
      - src/**
    docker:
      dockerfile: dev.Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - k8s-shared-environment.yaml
    - ../services/vacations-service/k8s.yaml
    - ../web/vacation-portal/k8s.yaml
  statusCheckDeadlineSeconds: 480
